### ISSUE TITLE
ReferenceError with latest Jekyll (2.5.3)

### ISSUE THREAD

**Issue by euler0** [drewsberry/jekyll-katex-block#1]
With Jekyll 2.5.3, I couldn't build the test site.

```
      Generating... 
  Liquid Exception: ReferenceError: Can't find variable: global in index.html
jekyll 2.5.3 | Error:  ReferenceError: Can't find variable: global
```

**Comment by drewsberry** [comment]
Would you mind running `jekyll build --trace`? I just updated to 2.5.3 and I'm getting a different, seemingly unrelated error.

**Comment by drewsberry** [comment]
I think this has to do withthe ExecJS runtime... Which are you using? (If you're not sure, just copy the output of 

```
ruby -e "require 'execjs'; puts ExecJS.runtime.name"
```

The reason I say this is that your error indicates that the JS runtime can't find `global`, whereas the error I'm getting is complaining because it can't find assign `global.katex` because again it can't find `global`. I think the problem may be with the first line of `katex.js`, where it says

```
... "undefined" != typeof window ? window.katex = e() : global.katex = e() ...
```

**Comment by drewsberry** [comment]
After further investigation, it seems this is caused by updating Jekyll to 2.5.3 causing ExecJS to update to 2.4.0. This works perfectly with ExecJS == 2.2.2, as before, but 2.3.0 and 2.4.0 both cause problems of the sort you encountered.

I'm not sure whether this is a change in the way ExecJS works or is a bug, but I'll raise an issue upstream. In the meantime I'll specify the version in the `Gemfile`.

Thanks very much for bringing this to my attention.

**Comment by drewsberry** [comment]
Upstream issue: https://github.com/rails/execjs/issues/14

**Comment by euler0** [comment]
@drewsberry Thank you for your investigation!
